# Generated by Django 5.2.4 on 2025-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=30)),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "todo",
            },
        ),
    ]
